#!/usr/bin/env python3
"""Generate a 2048-entry sine table.

Two output formats:

  hex (default):  one 16-bit unsigned offset-binary value per line.
                  Encoding: 0x0000 = -1.0, 0x8000 = 0.0, 0xFFFF = +1.0.
                  Consumed by Verilog `$readmemh` in src/spwm_tdm.v.

  c:              a C header declaring `static const int16_t sine_lut[2048]`
                  in signed two's-complement (-32767..+32767, midpoint 0).
                  Consumed by the ESP32-S3 firmware in esp32/src/.

Usage:
    python3 scripts/gen_sine_table.py            # hex to stdout
    python3 scripts/gen_sine_table.py --format hex > src/sine_init.hex
    python3 scripts/gen_sine_table.py --format c   > esp32/src/sine_lut.h
"""

import argparse
import math
import sys

ENTRIES = 2048
BITS = 16


def emit_hex(out):
    max_val = (1 << BITS) - 1  # 65535
    for i in range(ENTRIES):
        angle = 2.0 * math.pi * i / ENTRIES
        value = int(round(32767.5 + 32767.5 * math.sin(angle)))
        value = max(0, min(max_val, value))
        print(f"{value:04X}", file=out)


def emit_c(out):
    peak = 32767  # symmetric, avoid -32768 boundary
    print("// Auto-generated by scripts/gen_sine_table.py --format c", file=out)
    print("// 2048-entry signed sine table, range [-32767, +32767], midpoint 0.", file=out)
    print("#pragma once", file=out)
    print("#include <stdint.h>", file=out)
    print("", file=out)
    print(f"static const int16_t sine_lut[{ENTRIES}] = {{", file=out)
    line = []
    for i in range(ENTRIES):
        angle = 2.0 * math.pi * i / ENTRIES
        value = int(round(peak * math.sin(angle)))
        value = max(-peak, min(peak, value))
        line.append(f"{value:6d}")
        if len(line) == 8:
            print("    " + ", ".join(line) + ",", file=out)
            line = []
    if line:
        print("    " + ", ".join(line) + ",", file=out)
    print("};", file=out)


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--format", choices=("hex", "c"), default="hex")
    args = p.parse_args()
    if args.format == "hex":
        emit_hex(sys.stdout)
    else:
        emit_c(sys.stdout)


if __name__ == "__main__":
    main()
